### ISSUE TITLE
[Suggestion] Is it more appropriate to put A Perceptual Quality Metric for Video Frame Interpolation under Image Quality Assessment? 

### ISSUE THREAD

**Issue by star-journey** [DarrenPan/Awesome-ECCV2022-Low-Level-Vision#1]
Frame Interpolation - 插帧
A Perceptual Quality Metric for Video Frame Interpolation

Paper: https://arxiv.org/abs/2210.01879
Code: https://github.com/hqqxyy/VFIPS

Thank you for providing a collection of papers! 
I have read the paper above and I think its method is more related to video quality assessment. So I wonder if it is more appropriate to put it under Image Quality Assessment? That would be helpful for people in the field of quality assessment to find it.

**Comment by DarrenPan** [comment]
Thank you for your advice, I will put this paper in both VFI and IQA.
